
import { Player, PlayerRole, TeamData, Ground, Match, PlayerStats, NewsArticle, Format, Sponsorship } from './types';

export const MAX_SQUAD_SIZE = 16;
export const MIN_SQUAD_SIZE = 16;
export const MAX_FOREIGN_PLAYERS = 9; // Since min 7 local, max is 16 - 7 = 9

export const BRANDS = [
    { name: "Sike's", color: "text-yellow-500", style: "font-extrabold tracking-tight font-display", logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2l2.4 7.2h7.6l-6 4.8 2.4 7.2-6-4.8-6 4.8 2.4-7.2-6-4.8h7.6z" /></svg>' },
    { name: "Apex", color: "text-cyan-400", style: "font-sans tracking-widest uppercase", logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" /></svg>' },
    { name: "Malik", color: "text-red-600", style: "font-serif italic font-bold", logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M14.06 9.02l.92.92L3.92 21h16.16V23H3a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h1V9.02zM12 3a2 2 0 0 1 2 2v4h-4V5a2 2 0 0 1 2-2z"/></svg>' },
    { name: "G.S", color: "text-green-500", style: "font-mono font-bold", logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z" /></svg>' }
];

export const TV_CHANNELS = [
    { id: 'tv-prime', name: 'PrimeCast Ultra', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><rect x="2" y="4" width="20" height="16" rx="2" /><circle cx="12" cy="12" r="4" fill="white" fill-opacity="0.3"/><path d="M10 9l5 3-5 3V9z" fill="white"/></svg>', color: 'text-purple-500', minPopularity: 40, tier: 'Premium' },
    { id: 'tv-roar', name: 'Roar Sports', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2l3 6h6l-5 4 2 6-6-4-6 4 2-6-5-4h6z"/></svg>', color: 'text-red-600', minPopularity: 55, tier: 'Premium' },
    { id: 'tv-now', name: 'CricketNow HD', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M4 6h16v12H4z"/><path d="M8 10h8v4H8z" fill="white"/></svg>', color: 'text-blue-500', minPopularity: 30, tier: 'Standard' },
    { id: 'tv-apex', name: 'Apex Sports', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M2 12h20M2 12l10-9 10 9M2 12l10 9 10-9" stroke="currentColor" stroke-width="2" fill="none"/><circle cx="12" cy="12" r="3" fill="currentColor"/></svg>', color: 'text-cyan-400', minPopularity: 50, tier: 'Premium' },
];

export const TOURNAMENT_LOGOS = [
    { id: 'cup-1', name: 'Classic Cup', svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M5 2h14a1 1 0 0 1 1 1v4a3 3 0 0 1-3 3h-1v2h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-3v3h2a1 1 0 0 1 1 1v1H6v-1a1 1 0 0 1 1-1h2v-3H6a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h2v-2H7a3 3 0 0 1-3-3V3a1 1 0 0 1 1-1z"/></svg>' },
    { id: 'shield-1', name: 'Grand Shield', svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4zm0 10.99h7c-.53 4.12-3.28 7.79-7 8.94V12H5V6.3l7-3.11v8.8z"/></svg>' },
];

export const SPONSOR_THRESHOLDS = {
    [Format.T20]: { "Sike's": 40, "Apex": 35, "Malik": 30, "G.S": 25 },
    [Format.ODI]: { "Sike's": 45, "Apex": 40, "Malik": 30, "G.S": 25 },
    [Format.SHIELD]: { "Sike's": 40, "Apex": 35, "Malik": 30, "G.S": 25 },
    [Format.DEVELOPMENT_T20]: { "Sike's": 20, "Apex": 15, "Malik": 10, "G.S": 5 },
    [Format.RISE_T20]: { "Sike's": 30, "Apex": 25, "Malik": 20, "G.S": 15 },
    [Format.DEVELOPMENT_ODI]: { "Sike's": 25, "Apex": 20, "Malik": 15, "G.S": 10 },
    [Format.RISE_ODI]: { "Sike's": 35, "Apex": 30, "Malik": 25, "G.S": 20 },
    [Format.DEVELOPMENT_FIRST_CLASS]: { "Sike's": 20, "Apex": 15, "Malik": 10, "G.S": 5 },
    [Format.RISE_FIRST_CLASS]: { "Sike's": 30, "Apex": 25, "Malik": 20, "G.S": 15 },
};

export const INITIAL_SPONSORSHIPS: Record<Format, Sponsorship> = {
    [Format.T20]: { sponsorName: "Sike's", tournamentName: "Super Smash 26", logoColor: "text-yellow-500", tournamentLogo: TOURNAMENT_LOGOS[0].svg, tvChannel: "CricketNow HD", tvLogo: "" },
    [Format.ODI]: { sponsorName: "Apex", tournamentName: "Pro Cup 26", logoColor: "text-cyan-400", tournamentLogo: TOURNAMENT_LOGOS[0].svg, tvChannel: "Apex Sports", tvLogo: "" },
    [Format.SHIELD]: { sponsorName: "Malik", tournamentName: "Shield 26", logoColor: "text-red-600", tournamentLogo: TOURNAMENT_LOGOS[1].svg, tvChannel: "PrimeCast Ultra", tvLogo: "" },
    [Format.DEVELOPMENT_T20]: { sponsorName: "G.S", tournamentName: "Dev T20 Cup", logoColor: "text-green-500", tournamentLogo: TOURNAMENT_LOGOS[0].svg, tvChannel: "Dev Channel", tvLogo: "" },
    [Format.RISE_T20]: { sponsorName: "Malik", tournamentName: "Rise T20", logoColor: "text-blue-500", tournamentLogo: TOURNAMENT_LOGOS[0].svg, tvChannel: "Rise Sports", tvLogo: "" },
    [Format.DEVELOPMENT_ODI]: { sponsorName: "Apex", tournamentName: "Dev ODI Trophy", logoColor: "text-purple-500", tournamentLogo: TOURNAMENT_LOGOS[0].svg, tvChannel: "Apex Sports", tvLogo: "" },
    [Format.RISE_ODI]: { sponsorName: "Sike's", tournamentName: "Rise ODI Series", logoColor: "text-orange-500", tournamentLogo: TOURNAMENT_LOGOS[0].svg, tvChannel: "CricketNow HD", tvLogo: "" },
    [Format.DEVELOPMENT_FIRST_CLASS]: { sponsorName: "G.S", tournamentName: "Dev First-Class Cup", logoColor: "text-indigo-500", tournamentLogo: TOURNAMENT_LOGOS[1].svg, tvChannel: "PrimeCast Ultra", tvLogo: "" },
    [Format.RISE_FIRST_CLASS]: { sponsorName: "Malik", tournamentName: "Rise FC Series", logoColor: "text-emerald-500", tournamentLogo: TOURNAMENT_LOGOS[1].svg, tvChannel: "Rise Sports", tvLogo: "" },
};

export const TEAMS: TeamData[] = [
  { id: 'team1', name: 'KINGS', homeGround: 'KCG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M50 5 L95 25 L95 75 L50 95 L5 75 L5 25 Z" fill="#D4AF37" stroke="#8B7355" stroke-width="4"/><path d="M35 40 Q50 20 65 40 Q65 60 50 80 Q35 60 35 40" fill="#000"/><path d="M45 60 L55 60 L55 75 L45 75 Z" fill="#D4AF37"/><circle cx="50" cy="75" r="5" fill="#D4AF37"/></svg>', isYouthTeam: false },
  { id: 'team2', name: 'STARS', homeGround: 'SG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M50 10 L60 40 L90 40 L65 60 L75 90 L50 70 L25 90 L35 60 L10 40 L40 40 Z" fill="#1E3A8A" stroke="#3B82F6" stroke-width="2"/><circle cx="20" cy="20" r="4" fill="#FBBF24"/><circle cx="80" cy="20" r="4" fill="#FBBF24"/><circle cx="50" cy="5" r="3" fill="#FBBF24"/></svg>', isYouthTeam: false },
  { id: 'team3', name: 'SIXERS', homeGround: 'TG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="10" y="10" width="80" height="80" rx="20" fill="#DB2777" stroke="#9D174D" stroke-width="4"/><text x="50" y="70" font-family="Outfit" font-size="60" font-weight="900" fill="#FFFFFF" text-anchor="middle">6</text></svg>', isYouthTeam: false },
  { id: 'team4', name: 'GLADIATORS', homeGround: 'LWG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M20 20 H80 L80 60 Q50 95 20 60 Z" fill="#7F1D1D" stroke="#450A0A" stroke-width="4"/><path d="M40 35 H60 V55 Q50 65 40 55 Z" fill="#991B1B"/></svg>', isYouthTeam: false },
  { id: 'team5', name: 'HAWKS', homeGround: 'HGG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M20 30 Q50 10 80 30 L70 70 Q50 90 30 70 Z" fill="#9A3412" stroke="#7C2D12" stroke-width="4"/><path d="M60 40 Q75 45 60 55" fill="#FBBF24"/></svg>', isYouthTeam: false },
  { id: 'team6', name: 'EAGLES', homeGround: 'MCG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M10 40 Q50 10 90 40 L80 80 Q50 60 20 80 Z" fill="#1E40AF" stroke="#1E3A8A" stroke-width="4"/><path d="M45 35 L55 35 L50 50 Z" fill="#FBBF24"/></svg>', isYouthTeam: false },
  { id: 'team7', name: 'TITANS', homeGround: 'KCG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="20" y="20" width="60" height="60" fill="#4B5563" stroke="#1F2937" stroke-width="4"/><path d="M30 30 L70 70 M70 30 L30 70" stroke="#FFFFFF" stroke-width="4"/></svg>', isYouthTeam: false },
  { id: 'team8', name: 'WARRIORS', homeGround: 'SG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M50 10 L80 80 L20 80 Z" fill="#B91C1C" stroke="#7F1D1D" stroke-width="4"/><rect x="45" y="30" width="10" height="40" fill="#FFFFFF"/></svg>', isYouthTeam: false },
  { id: 'team9', name: 'STRIKERS', homeGround: 'TG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="#F59E0B" stroke="#B45309" stroke-width="4"/><path d="M30 50 L70 50 M50 30 L50 70" stroke="#FFFFFF" stroke-width="8" stroke-linecap="round"/></svg>', isYouthTeam: false },
  { id: 'team10', name: 'ROYALS', homeGround: 'LWG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M10 80 L20 20 L40 50 L60 20 L80 50 L90 80 Z" fill="#7C3AED" stroke="#5B21B6" stroke-width="4"/><circle cx="50" cy="70" r="5" fill="#FBBF24"/></svg>', isYouthTeam: false },
  { id: 'team11', name: 'PANTHERS', homeGround: 'HGG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M20 40 Q50 10 80 40 L80 80 L20 80 Z" fill="#111827" stroke="#374151" stroke-width="2"/><circle cx="35" cy="45" r="4" fill="#EF4444"/><circle cx="65" cy="45" r="4" fill="#EF4444"/></svg>', isYouthTeam: false },
  { id: 'team12', name: 'FALCONS', homeGround: 'MCG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M10 50 Q50 10 90 50 Q50 90 10 50" fill="#2563EB" stroke="#1E40AF" stroke-width="4"/><path d="M40 50 L60 50 L50 40 Z" fill="#FFFFFF"/></svg>', isYouthTeam: false },
  { id: 'team13', name: 'RIDERS', homeGround: 'KCG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="10" y="30" width="80" height="40" rx="10" fill="#059669" stroke="#047857" stroke-width="4"/><circle cx="30" cy="70" r="10" fill="#111827"/><circle cx="70" cy="70" r="10" fill="#111827"/></svg>', isYouthTeam: false },
  { id: 'team14', name: 'CHARGERS', homeGround: 'SG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M60 10 L30 50 H50 L20 90 L80 40 H60 L80 10 Z" fill="#EAB308" stroke="#A16207" stroke-width="4"/></svg>', isYouthTeam: false },
  { id: 'team15', name: 'BLAZERS', homeGround: 'TG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M50 10 Q70 40 50 90 Q30 40 50 10" fill="#DC2626" stroke="#991B1B" stroke-width="4"/><path d="M50 30 Q65 50 50 80 Q35 50 50 30" fill="#F97316"/></svg>', isYouthTeam: false },
  { id: 'team16', name: 'KNIGHTS', homeGround: 'LWG', logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M25 20 L75 20 L75 60 Q50 90 25 60 Z" fill="#4B5563" stroke="#1F2937" stroke-width="4"/><rect x="45" y="10" width="10" height="20" fill="#1F2937"/></svg>', isYouthTeam: false },
];

export const GROUPS = {
    A: ['team1', 'team2', 'team3', 'team4', 'team7', 'team8', 'team9', 'team10'],
    B: ['team5', 'team6', 'team11', 'team12', 'team13', 'team14', 'team15', 'team16']
};

export const GROUNDS: Ground[] = [
  { name: "Keenjhur Cricket Ground", code: "KCG", pitch: "Balanced Sporting Pitch", dimensions: "70m / 68m", weather: "Sunny", boundarySize: "Medium", outfieldSpeed: "Fast", capacity: 25000 },
  { name: "School Ground", code: "SG", pitch: "Dusty Spinner’s Haven", dimensions: "62m / 60m", weather: "Dry", boundarySize: "Small", outfieldSpeed: "Slow", capacity: 5000 },
  { name: "Transformer Ground", code: "TG", pitch: "Green Top", dimensions: "75m / 72m", weather: "Overcast", boundarySize: "Large", outfieldSpeed: "Medium", capacity: 12000 },
  { name: "Lake Way Ground", code: "LWG", pitch: "Batting Paradise", dimensions: "65m / 65m", weather: "Sunny", boundarySize: "Small", outfieldSpeed: "Lightning", capacity: 18000 },
  { name: "Home Gate Ground", code: "HGG", pitch: "Dead Slow Track", dimensions: "68m / 68m", weather: "Humid", boundarySize: "Medium", outfieldSpeed: "Slow", capacity: 8000 },
  { name: "Mosque Cricket Ground", code: "MCG", pitch: "Cracked Worn Surface", dimensions: "72m / 70m", weather: "Dry", boundarySize: "Large", outfieldSpeed: "Medium", capacity: 15000 },
];

export const PITCH_TYPES = [ "Balanced Sporting Pitch", "Dusty Spinner’s Haven", "Green Top", "Batting Paradise", "Dead Slow Track", "Cracked Worn Surface" ];

export const generateSingleFormatInitialStats = (): PlayerStats => ({
    matches: 0, runs: 0, highestScore: 0, average: 0, strikeRate: 0, ballsFaced: 0, dismissals: 0,
    hundreds: 0, fifties: 0, thirties: 0, fours: 0, sixes: 0, fastestFifty: 0, fastestHundred: 0,
    wickets: 0, economy: 0, bestBowling: '-', bestBowlingWickets: 0, bestBowlingRuns: 0,
    bowlingAverage: 0, ballsBowled: 0, runsConceded: 0, threeWicketHauls: 0, fiveWicketHauls: 0,
    catches: 0, runOuts: 0, manOfTheMatchAwards: 0,
    ppRuns: 0, ppBalls: 0, ppWickets: 0, ppRunsConceded: 0, ppBallsBowled: 0,
    midRuns: 0, midBalls: 0, midWickets: 0, midRunsConceded: 0, midBallsBowled: 0,
    deathRuns: 0, deathBalls: 0, deathWickets: 0, deathRunsConceded: 0, deathBallsBowled: 0,
    ones: 0, twos: 0, threes: 0, dots: 0,
    runsByPosition: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0 },
});

export const generateInitialStats = (): { [key in Format]: PlayerStats } => {
    const stats: any = {};
    Object.values(Format).forEach(f => stats[f] = generateSingleFormatInitialStats());
    return stats;
};

// --- RAW PLAYER DATA (2026 EDITION) ---
const playersRaw: any[] = [
    // INTERNATIONAL PLAYERS
    { id: 'int-1', name: 'A. Haddin', nationality: 'Australia', role: PlayerRole.ALL_ROUNDER, battingSkill: 65, secondarySkill: 56, style: 'A', isOpener: false, isForeign: true, age: 34, fielding: 70, accuracy: 60, potential: 68 },
    { id: 'int-2', name: 'Langer', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 72, style: 'D', isOpener: false, isForeign: true, age: 31, fielding: 65, accuracy: 75, potential: 74 },
    { id: 'int-3', name: 'Parsh', nationality: 'Australia', role: PlayerRole.WICKET_KEEPER, battingSkill: 76, secondarySkill: 70, style: 'N', isOpener: true, isForeign: true, age: 26, fielding: 75, accuracy: 50, potential: 82 },
    { id: 'int-4', name: 'Mausechate', nationality: 'Australia', role: PlayerRole.BATSMAN, battingSkill: 69, secondarySkill: 23, style: 'A', isOpener: false, isForeign: true, age: 24, fielding: 60, accuracy: 40, potential: 78 },
    { id: 'int-5', name: 'Wade', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 25, secondarySkill: 84, style: 'D', isOpener: false, isForeign: true, age: 28, fielding: 55, accuracy: 82, potential: 86 },
    { id: 'int-6', name: 'Lance', nationality: 'Australia', role: PlayerRole.BATSMAN, battingSkill: 76, secondarySkill: 10, style: 'N', isOpener: true, isForeign: true, age: 27, fielding: 65, accuracy: 30, potential: 80 },
    { id: 'int-7', name: 'M.G. Glaxen', nationality: 'Australia', role: PlayerRole.ALL_ROUNDER, battingSkill: 82, secondarySkill: 65, style: 'A', isOpener: true, isForeign: true, age: 29, fielding: 80, accuracy: 65, potential: 85 },
    { id: 'int-8', name: 'J. Harris', nationality: 'Australia', role: PlayerRole.ALL_ROUNDER, battingSkill: 56, secondarySkill: 45, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 60, accuracy: 55, potential: 72 },
    { id: 'int-9', name: 'Lin', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 34, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 22, fielding: 60, accuracy: 70, potential: 78 },
    { id: 'int-10', name: 'Wilton', nationality: 'Australia', role: PlayerRole.ALL_ROUNDER, battingSkill: 72, secondarySkill: 64, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 70, accuracy: 68, potential: 80 },
    { id: 'int-11', name: 'Waller', nationality: 'New Zealand', role: PlayerRole.FAST_BOWLER, battingSkill: 23, secondarySkill: 67, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 62, accuracy: 72, potential: 75 },
    { id: 'int-12', name: 'B. Rington', nationality: 'New Zealand', role: PlayerRole.ALL_ROUNDER, battingSkill: 45, secondarySkill: 56, style: 'N', isOpener: false, isForeign: true, age: 26, fielding: 65, accuracy: 62, potential: 70 },
    { id: 'int-13', name: 'Addams', nationality: 'New Zealand', role: PlayerRole.ALL_ROUNDER, battingSkill: 55, secondarySkill: 45, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 68, accuracy: 58, potential: 72 },
    { id: 'int-14', name: 'S. Warner', nationality: 'New Zealand', role: PlayerRole.BATSMAN, battingSkill: 76, secondarySkill: 33, style: 'A', isOpener: true, isForeign: true, age: 34, fielding: 72, accuracy: 50, potential: 80 },
    { id: 'int-15', name: 'Sprike', nationality: 'New Zealand', role: PlayerRole.WICKET_KEEPER, battingSkill: 80, secondarySkill: 75, style: 'A', isOpener: true, isForeign: true, age: 29, fielding: 82, accuracy: 55, potential: 84 },
    { id: 'int-16', name: 'Jordan', nationality: 'West Indies', role: PlayerRole.FAST_BOWLER, battingSkill: 23, secondarySkill: 66, style: 'N', isOpener: false, isForeign: true, age: 30, fielding: 65, accuracy: 70, potential: 70 },
    { id: 'int-17', name: 'N. Fill', nationality: 'West Indies', role: PlayerRole.SPIN_BOWLER, battingSkill: 22, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 60, accuracy: 75, potential: 80 },
    { id: 'int-18', name: 'A. Chadwick', nationality: 'West Indies', role: PlayerRole.WICKET_KEEPER, battingSkill: 73, secondarySkill: 72, style: 'A', isOpener: true, isForeign: true, age: 26, fielding: 78, accuracy: 50, potential: 82 },
    { id: 'int-19', name: 'Sriwardna', nationality: 'Sri Lanka', role: PlayerRole.BATSMAN, battingSkill: 67, secondarySkill: 15, style: 'D', isOpener: false, isForeign: true, age: 32, fielding: 65, accuracy: 40, potential: 70 },
    { id: 'int-20', name: 'C. Dhanushka', nationality: 'Sri Lanka', role: PlayerRole.ALL_ROUNDER, battingSkill: 45, secondarySkill: 66, style: 'D', isOpener: false, isForeign: true, age: 28, fielding: 62, accuracy: 72, potential: 75 },
    { id: 'int-21', name: 'James', nationality: 'South Africa', role: PlayerRole.ALL_ROUNDER, battingSkill: 63, secondarySkill: 66, style: 'A', isOpener: false, isForeign: true, age: 27, fielding: 72, accuracy: 70, potential: 78 },
    { id: 'int-22', name: 'Aram', nationality: 'South Africa', role: PlayerRole.ALL_ROUNDER, battingSkill: 45, secondarySkill: 66, style: 'D', isOpener: false, isForeign: true, age: 24, fielding: 65, accuracy: 68, potential: 76 },
    { id: 'int-23', name: 'N. Colin', nationality: 'England', role: PlayerRole.ALL_ROUNDER, battingSkill: 70, secondarySkill: 61, style: 'N', isOpener: false, isForeign: true, age: 28, fielding: 70, accuracy: 65, potential: 78 },
    { id: 'int-24', name: 'D. Quentin', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 56, secondarySkill: 23, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 62, accuracy: 40, potential: 72 },

    // WEST INDIES
    { id: 'wi-1', name: 'R. Lewis', nationality: 'West Indies', role: PlayerRole.BATSMAN, battingSkill: 78, secondarySkill: 20, style: 'A', isOpener: false, isForeign: true, age: 28, fielding: 70, accuracy: 40, potential: 88 },
    { id: 'wi-2', name: 'C. Holder', nationality: 'West Indies', role: PlayerRole.ALL_ROUNDER, battingSkill: 70, secondarySkill: 65, style: 'NA', isOpener: false, isForeign: true, age: 27, fielding: 72, accuracy: 68, potential: 82 },
    { id: 'wi-3', name: 'D. Kingman', nationality: 'West Indies', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 18, style: 'A', isOpener: false, isForeign: true, age: 25, fielding: 68, accuracy: 35, potential: 84 },
    { id: 'wi-4', name: 'S. Powell', nationality: 'West Indies', role: PlayerRole.BATSMAN, battingSkill: 68, secondarySkill: 15, style: 'N', isOpener: false, isForeign: true, age: 31, fielding: 65, accuracy: 30, potential: 78 },
    { id: 'wi-5', name: 'M. Grant', nationality: 'West Indies', role: PlayerRole.ALL_ROUNDER, battingSkill: 65, secondarySkill: 60, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 62, accuracy: 64, potential: 75 },
    { id: 'wi-6', name: 'T. Edwards', nationality: 'West Indies', role: PlayerRole.SPIN_BOWLER, battingSkill: 40, secondarySkill: 67, style: 'D', isOpener: false, isForeign: true, age: 26, fielding: 58, accuracy: 72, potential: 78 },
    { id: 'wi-7', name: 'K. Brooks', nationality: 'West Indies', role: PlayerRole.FAST_BOWLER, battingSkill: 28, secondarySkill: 70, style: 'D', isOpener: false, isForeign: true, age: 23, fielding: 60, accuracy: 75, potential: 80 },
    { id: 'wi-8', name: 'J. Allen', nationality: 'West Indies', role: PlayerRole.FAST_BOWLER, battingSkill: 26, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 22, fielding: 55, accuracy: 72, potential: 78 },
    { id: 'wi-9', name: 'R. Baptiste', nationality: 'West Indies', role: PlayerRole.ALL_ROUNDER, battingSkill: 63, secondarySkill: 62, style: 'NA', isOpener: false, isForeign: true, age: 29, fielding: 65, accuracy: 65, potential: 76 },
    { id: 'wi-10', name: 'A. Sinclair', nationality: 'West Indies', role: PlayerRole.BATSMAN, battingSkill: 66, secondarySkill: 22, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 60, accuracy: 42, potential: 78 },
    { id: 'wi-11', name: 'L. Thomas', nationality: 'West Indies', role: PlayerRole.WICKET_KEEPER, battingSkill: 60, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 75, accuracy: 50, potential: 75 },
    { id: 'wi-12', name: 'P. Johnson', nationality: 'West Indies', role: PlayerRole.FAST_BOWLER, battingSkill: 24, secondarySkill: 69, style: 'D', isOpener: false, isForeign: true, age: 27, fielding: 58, accuracy: 74, potential: 76 },

    // SRI LANKA
    { id: 'sl-1', name: 'R. Jayalath', nationality: 'Sri Lanka', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 12, style: 'N', isOpener: true, isForeign: true, age: 26, fielding: 68, accuracy: 35, potential: 84 },
    { id: 'sl-2', name: 'K. Perera', nationality: 'Sri Lanka', role: PlayerRole.BATSMAN, battingSkill: 74, secondarySkill: 18, style: 'A', isOpener: true, isForeign: true, age: 33, fielding: 70, accuracy: 40, potential: 82 },
    { id: 'sl-3', name: 'S. Fernando', nationality: 'Sri Lanka', role: PlayerRole.BATSMAN, battingSkill: 70, secondarySkill: 15, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 65, accuracy: 30, potential: 80 },
    { id: 'sl-4', name: 'N. Silva', nationality: 'Sri Lanka', role: PlayerRole.BATSMAN, battingSkill: 68, secondarySkill: 10, style: 'D', isOpener: false, isForeign: true, age: 29, fielding: 62, accuracy: 32, potential: 76 },
    { id: 'sl-5', name: 'A. Wickram', nationality: 'Sri Lanka', role: PlayerRole.BATSMAN, battingSkill: 66, secondarySkill: 0, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 60, accuracy: 25, potential: 78 },
    { id: 'sl-6', name: 'M. Gunasekara', nationality: 'Sri Lanka', role: PlayerRole.WICKET_KEEPER, battingSkill: 65, secondarySkill: 72, style: 'N', isOpener: false, isForeign: true, age: 27, fielding: 80, accuracy: 50, potential: 78 },
    { id: 'sl-7', name: 'D. Samar', nationality: 'Sri Lanka', role: PlayerRole.WICKET_KEEPER, battingSkill: 70, secondarySkill: 78, style: 'A', isOpener: false, isForeign: true, age: 25, fielding: 82, accuracy: 55, potential: 84 },
    { id: 'sl-8', name: 'L. Karunaratne', nationality: 'Sri Lanka', role: PlayerRole.WICKET_KEEPER, battingSkill: 60, secondarySkill: 68, style: 'D', isOpener: false, isForeign: true, age: 31, fielding: 75, accuracy: 45, potential: 72 },
    { id: 'sl-9', name: 'H. Rajapaksa', nationality: 'Sri Lanka', role: PlayerRole.ALL_ROUNDER, battingSkill: 68, secondarySkill: 62, style: 'NA', isOpener: false, isForeign: true, age: 32, fielding: 72, accuracy: 65, potential: 78 },
    { id: 'sl-10', name: 'P. Mathews', nationality: 'Sri Lanka', role: PlayerRole.ALL_ROUNDER, battingSkill: 65, secondarySkill: 60, style: 'N', isOpener: false, isForeign: true, age: 35, fielding: 68, accuracy: 62, potential: 75 },
    { id: 'sl-11', name: 'T. Mendis', nationality: 'Sri Lanka', role: PlayerRole.ALL_ROUNDER, battingSkill: 60, secondarySkill: 58, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 65, accuracy: 60, potential: 74 },
    { id: 'sl-12', name: 'S. Kulasekara', nationality: 'Sri Lanka', role: PlayerRole.ALL_ROUNDER, battingSkill: 58, secondarySkill: 64, style: 'D', isOpener: false, isForeign: true, age: 33, fielding: 62, accuracy: 68, potential: 70 },
    { id: 'sl-13', name: 'R. Jayasinghe', nationality: 'Sri Lanka', role: PlayerRole.SPIN_BOWLER, battingSkill: 40, secondarySkill: 70, style: 'D', isOpener: false, isForeign: true, age: 26, fielding: 58, accuracy: 75, potential: 76 },
    { id: 'sl-14', name: 'M. Dananjaya', nationality: 'Sri Lanka', role: PlayerRole.SPIN_BOWLER, battingSkill: 38, secondarySkill: 72, style: 'N', isOpener: false, isForeign: true, age: 31, fielding: 60, accuracy: 78, potential: 78 },
    { id: 'sl-15', name: 'K. Silva', nationality: 'Sri Lanka', role: PlayerRole.SPIN_BOWLER, battingSkill: 42, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 28, fielding: 55, accuracy: 72, potential: 75 },
    { id: 'sl-16', name: 'A. Herath', nationality: 'Sri Lanka', role: PlayerRole.SPIN_BOWLER, battingSkill: 35, secondarySkill: 75, style: 'D', isOpener: false, isForeign: true, age: 36, fielding: 52, accuracy: 82, potential: 80 },
    { id: 'sl-17', name: 'L. Kumara', nationality: 'Sri Lanka', role: PlayerRole.FAST_BOWLER, battingSkill: 28, secondarySkill: 78, style: 'N', isOpener: false, isForeign: true, age: 26, fielding: 60, accuracy: 82, potential: 85 },
    { id: 'sl-18', name: 'S. Madushan', nationality: 'Sri Lanka', role: PlayerRole.FAST_BOWLER, battingSkill: 26, secondarySkill: 74, style: 'D', isOpener: false, isForeign: true, age: 24, fielding: 55, accuracy: 78, potential: 82 },
    { id: 'sl-19', name: 'N. Pradeep', nationality: 'Sri Lanka', role: PlayerRole.FAST_BOWLER, battingSkill: 24, secondarySkill: 72, style: 'N', isOpener: false, isForeign: true, age: 33, fielding: 52, accuracy: 76, potential: 78 },
    { id: 'sl-20', name: 'C. Lakmal', nationality: 'Sri Lanka', role: PlayerRole.FAST_BOWLER, battingSkill: 25, secondarySkill: 70, style: 'D', isOpener: false, isForeign: true, age: 34, fielding: 58, accuracy: 75, potential: 75 },
    { id: 'sl-21', name: 'R. Pathirana', nationality: 'Sri Lanka', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 76, style: 'A', isOpener: false, isForeign: true, age: 21, fielding: 62, accuracy: 78, potential: 90 },
    { id: 'sl-22', name: 'M. Fernando', nationality: 'Sri Lanka', role: PlayerRole.FAST_BOWLER, battingSkill: 30, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 55, accuracy: 72, potential: 80 },
    { id: 'sl-23', name: 'I. Peris', nationality: 'Sri Lanka', role: PlayerRole.BATSMAN, battingSkill: 62, secondarySkill: 18, style: 'N', isOpener: false, isForeign: true, age: 28, fielding: 65, accuracy: 40, potential: 72 },
    { id: 'sl-24', name: 'D. Alwis', nationality: 'Sri Lanka', role: PlayerRole.ALL_ROUNDER, battingSkill: 57, secondarySkill: 55, style: 'NA', isOpener: false, isForeign: true, age: 26, fielding: 62, accuracy: 58, potential: 70 },
    { id: 'sl-25', name: 'S. Nissanka', nationality: 'Sri Lanka', role: PlayerRole.BATSMAN, battingSkill: 64, secondarySkill: 12, style: 'A', isOpener: false, isForeign: true, age: 24, fielding: 68, accuracy: 35, potential: 78 },
    { id: 'sl-26', name: 'T. Bandara', nationality: 'Sri Lanka', role: PlayerRole.SPIN_BOWLER, battingSkill: 36, secondarySkill: 65, style: 'D', isOpener: false, isForeign: true, age: 22, fielding: 54, accuracy: 70, potential: 74 },
    { id: 'sl-27', name: 'K. Senanayake', nationality: 'Sri Lanka', role: PlayerRole.FAST_BOWLER, battingSkill: 26, secondarySkill: 66, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 52, accuracy: 70, potential: 76 },
    { id: 'sl-28', name: 'J. Abeyratne', nationality: 'Sri Lanka', role: PlayerRole.WICKET_KEEPER, battingSkill: 58, secondarySkill: 65, style: 'D', isOpener: false, isForeign: true, age: 29, fielding: 70, accuracy: 45, potential: 72 },

    // SOUTH AFRICA
    { id: 'sa-1', name: 'Q. van Rooyen', nationality: 'South Africa', role: PlayerRole.BATSMAN, battingSkill: 76, secondarySkill: 22, style: 'A', isOpener: true, isForeign: true, age: 28, fielding: 75, accuracy: 45, potential: 88 },
    { id: 'sa-2', name: 'L. Pretorius', nationality: 'South Africa', role: PlayerRole.BATSMAN, battingSkill: 74, secondarySkill: 18, style: 'N', isOpener: true, isForeign: true, age: 26, fielding: 72, accuracy: 40, potential: 85 },
    { id: 'sa-3', name: 'T. Mbeki', nationality: 'South Africa', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 15, style: 'D', isOpener: false, isForeign: true, age: 31, fielding: 68, accuracy: 35, potential: 80 },
    { id: 'sa-4', name: 'R. Malan', nationality: 'South Africa', role: PlayerRole.BATSMAN, battingSkill: 70, secondarySkill: 12, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 65, accuracy: 32, potential: 82 },
    { id: 'sa-5', name: 'S. de Kockton', nationality: 'South Africa', role: PlayerRole.BATSMAN, battingSkill: 68, secondarySkill: 10, style: 'A', isOpener: false, isForeign: true, age: 30, fielding: 62, accuracy: 30, potential: 78 },
    { id: 'sa-6', name: 'J. Kruger', nationality: 'South Africa', role: PlayerRole.WICKET_KEEPER, battingSkill: 72, secondarySkill: 80, style: 'NA', isOpener: false, isForeign: true, age: 27, fielding: 88, accuracy: 55, potential: 86 },
    { id: 'sa-7', name: 'B. van Dyk', nationality: 'South Africa', role: PlayerRole.WICKET_KEEPER, battingSkill: 65, secondarySkill: 72, style: 'D', isOpener: false, isForeign: true, age: 25, fielding: 80, accuracy: 48, potential: 78 },
    { id: 'sa-8', name: 'A. Moller', nationality: 'South Africa', role: PlayerRole.WICKET_KEEPER, battingSkill: 60, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 75, accuracy: 45, potential: 75 },
    { id: 'sa-9', name: 'H. du Pless', nationality: 'South Africa', role: PlayerRole.ALL_ROUNDER, battingSkill: 68, secondarySkill: 62, style: 'NA', isOpener: false, isForeign: true, age: 33, fielding: 74, accuracy: 65, potential: 80 },
    { id: 'sa-10', name: 'S. Ngidi', nationality: 'South Africa', role: PlayerRole.ALL_ROUNDER, battingSkill: 55, secondarySkill: 65, style: 'N', isOpener: false, isForeign: true, age: 28, fielding: 68, accuracy: 72, potential: 82 },
    { id: 'sa-11', name: 'K. Rabada', nationality: 'South Africa', role: PlayerRole.ALL_ROUNDER, battingSkill: 58, secondarySkill: 70, style: 'A', isOpener: false, isForeign: true, age: 29, fielding: 82, accuracy: 85, potential: 92 },
    { id: 'sa-12', name: 'T. Maharaj', nationality: 'South Africa', role: PlayerRole.SPIN_BOWLER, battingSkill: 42, secondarySkill: 72, style: 'D', isOpener: false, isForeign: true, age: 34, fielding: 65, accuracy: 80, potential: 78 },
    { id: 'sa-13', name: 'L. Shamsi', nationality: 'South Africa', role: PlayerRole.SPIN_BOWLER, battingSkill: 38, secondarySkill: 75, style: 'N', isOpener: false, isForeign: true, age: 35, fielding: 60, accuracy: 82, potential: 80 },
    { id: 'sa-14', name: 'A. Botha', nationality: 'South Africa', role: PlayerRole.SPIN_BOWLER, battingSkill: 40, secondarySkill: 68, style: 'D', isOpener: false, isForeign: true, age: 27, fielding: 58, accuracy: 74, potential: 75 },
    { id: 'sa-15', name: 'J. Nortje', nationality: 'South Africa', role: PlayerRole.FAST_BOWLER, battingSkill: 28, secondarySkill: 85, style: 'A', isOpener: false, isForeign: true, age: 30, fielding: 62, accuracy: 88, potential: 90 },
    { id: 'sa-16', name: 'K. Steynson', nationality: 'South Africa', role: PlayerRole.FAST_BOWLER, battingSkill: 26, secondarySkill: 82, style: 'N', isOpener: false, isForeign: true, age: 31, fielding: 60, accuracy: 85, potential: 86 },
    { id: 'sa-17', name: 'P. Coetzee', nationality: 'South Africa', role: PlayerRole.FAST_BOWLER, battingSkill: 24, secondarySkill: 80, style: 'D', isOpener: false, isForeign: true, age: 22, fielding: 58, accuracy: 82, potential: 92 },
    { id: 'sa-18', name: 'M. Jansen', nationality: 'South Africa', role: PlayerRole.FAST_BOWLER, battingSkill: 30, secondarySkill: 78, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 65, accuracy: 80, potential: 88 },
    { id: 'sa-19', name: 'R. Olivier', nationality: 'South Africa', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 76, style: 'D', isOpener: false, isForeign: true, age: 32, fielding: 55, accuracy: 78, potential: 78 },
    { id: 'sa-20', name: 'S. Maphosa', nationality: 'South Africa', role: PlayerRole.FAST_BOWLER, battingSkill: 25, secondarySkill: 74, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 58, accuracy: 75, potential: 80 },
    { id: 'sa-21', name: 'E. Lutho', nationality: 'South Africa', role: PlayerRole.FAST_BOWLER, battingSkill: 27, secondarySkill: 72, style: 'N', isOpener: false, isForeign: true, age: 26, fielding: 60, accuracy: 74, potential: 76 },
    { id: 'sa-22', name: 'D. Klaasen', nationality: 'South Africa', role: PlayerRole.BATSMAN, battingSkill: 66, secondarySkill: 15, style: 'A', isOpener: false, isForeign: true, age: 34, fielding: 70, accuracy: 40, potential: 78 },
    { id: 'sa-23', name: 'P. Adams', nationality: 'South Africa', role: PlayerRole.ALL_ROUNDER, battingSkill: 60, secondarySkill: 58, style: 'NA', isOpener: false, isForeign: true, age: 27, fielding: 65, accuracy: 62, potential: 74 },
    { id: 'sa-24', name: 'Z. Maseko', nationality: 'South Africa', role: PlayerRole.SPIN_BOWLER, battingSkill: 35, secondarySkill: 65, style: 'D', isOpener: false, isForeign: true, age: 21, fielding: 54, accuracy: 70, potential: 75 },
    { id: 'sa-25', name: 'Nel', nationality: 'South Africa', role: PlayerRole.FAST_BOWLER, battingSkill: 23, secondarySkill: 70, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 56, accuracy: 72, potential: 72 },
    { id: 'sa-26', name: 'A. Fischer', nationality: 'South Africa', role: PlayerRole.BATSMAN, battingSkill: 64, secondarySkill: 20, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 65, accuracy: 42, potential: 76 },
    { id: 'sa-27', name: 'C. Pretor', nationality: 'South Africa', role: PlayerRole.ALL_ROUNDER, battingSkill: 57, secondarySkill: 55, style: 'N', isOpener: false, isForeign: true, age: 26, fielding: 62, accuracy: 58, potential: 70 },
    { id: 'sa-28', name: 'J. Swart', nationality: 'South Africa', role: PlayerRole.WICKET_KEEPER, battingSkill: 58, secondarySkill: 66, style: 'D', isOpener: false, isForeign: true, age: 28, fielding: 72, accuracy: 45, potential: 74 },

    // ENGLAND
    { id: 'en-1', name: 'R. Haleson', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 75, secondarySkill: 18, style: 'A', isOpener: true, isForeign: true, age: 35, fielding: 72, accuracy: 38, potential: 80 },
    { id: 'en-2', name: 'T. Crawleyton', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 73, secondarySkill: 15, style: 'N', isOpener: true, isForeign: true, age: 28, fielding: 70, accuracy: 35, potential: 82 },
    { id: 'en-3', name: 'J. Rootman', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 78, secondarySkill: 25, style: 'NA', isOpener: false, isForeign: true, age: 35, fielding: 85, accuracy: 55, potential: 85 },
    { id: 'en-4', name: 'B. Stokesley', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 35, style: 'A', isOpener: false, isForeign: true, age: 34, fielding: 92, accuracy: 65, potential: 88 },
    { id: 'en-5', name: 'O. Popeham', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 70, secondarySkill: 12, style: 'N', isOpener: false, isForeign: true, age: 28, fielding: 80, accuracy: 30, potential: 84 },
    { id: 'en-6', name: 'J. Butleron', nationality: 'England', role: PlayerRole.WICKET_KEEPER, battingSkill: 76, secondarySkill: 82, style: 'A', isOpener: false, isForeign: true, age: 35, fielding: 90, accuracy: 60, potential: 85 },
    { id: 'en-7', name: 'S. Foakesby', nationality: 'England', role: PlayerRole.WICKET_KEEPER, battingSkill: 65, secondarySkill: 78, style: 'D', isOpener: false, isForeign: true, age: 33, fielding: 95, accuracy: 48, potential: 75 },
    { id: 'en-8', name: 'T. Bairston', nationality: 'England', role: PlayerRole.WICKET_KEEPER, battingSkill: 68, secondarySkill: 72, style: 'NA', isOpener: false, isForeign: true, age: 36, fielding: 82, accuracy: 55, potential: 78 },
    { id: 'en-9', name: 'L. Woakeson', nationality: 'England', role: PlayerRole.ALL_ROUNDER, battingSkill: 60, secondarySkill: 65, style: 'N', isOpener: false, isForeign: true, age: 37, fielding: 75, accuracy: 78, potential: 75 },
    { id: 'en-10', name: 'M. Aliyah', nationality: 'England', role: PlayerRole.ALL_ROUNDER, battingSkill: 58, secondarySkill: 68, style: 'NA', isOpener: false, isForeign: true, age: 38, fielding: 72, accuracy: 75, potential: 72 },
    { id: 'en-11', name: 'S. Curranley', nationality: 'England', role: PlayerRole.ALL_ROUNDER, battingSkill: 62, secondarySkill: 66, style: 'A', isOpener: false, isForeign: true, age: 27, fielding: 80, accuracy: 72, potential: 88 },
    { id: 'en-12', name: 'A. Rashidon', nationality: 'England', role: PlayerRole.SPIN_BOWLER, battingSkill: 40, secondarySkill: 74, style: 'N', isOpener: false, isForeign: true, age: 38, fielding: 65, accuracy: 82, potential: 78 },
    { id: 'en-13', name: 'J. Leachman', nationality: 'England', role: PlayerRole.SPIN_BOWLER, battingSkill: 38, secondarySkill: 72, style: 'D', isOpener: false, isForeign: true, age: 34, fielding: 58, accuracy: 80, potential: 74 },
    { id: 'en-14', name: 'R. Besset', nationality: 'England', role: PlayerRole.SPIN_BOWLER, battingSkill: 36, secondarySkill: 68, style: 'D', isOpener: false, isForeign: true, age: 28, fielding: 60, accuracy: 74, potential: 76 },
    { id: 'en-15', name: 'J. Andersonic', nationality: 'England', role: PlayerRole.FAST_BOWLER, battingSkill: 24, secondarySkill: 82, style: 'D', isOpener: false, isForeign: true, age: 43, fielding: 70, accuracy: 95, potential: 82 },
    { id: 'en-16', name: 'S. Broadley', nationality: 'England', role: PlayerRole.FAST_BOWLER, battingSkill: 26, secondarySkill: 80, style: 'N', isOpener: false, isForeign: true, age: 39, fielding: 68, accuracy: 88, potential: 80 },
    { id: 'en-17', name: 'M. Woodson', nationality: 'England', role: PlayerRole.FAST_BOWLER, battingSkill: 28, secondarySkill: 85, style: 'A', isOpener: false, isForeign: true, age: 36, fielding: 62, accuracy: 82, potential: 85 },
    { id: 'en-18', name: 'O. Stoneham', nationality: 'England', role: PlayerRole.FAST_BOWLER, battingSkill: 25, secondarySkill: 78, style: 'N', isOpener: false, isForeign: true, age: 32, fielding: 58, accuracy: 76, potential: 84 },
    { id: 'en-19', name: 'C. Archeron', nationality: 'England', role: PlayerRole.FAST_BOWLER, battingSkill: 30, secondarySkill: 88, style: 'A', isOpener: false, isForeign: true, age: 31, fielding: 70, accuracy: 85, potential: 92 },
    { id: 'en-20', name: 'D. Willeyson', nationality: 'England', role: PlayerRole.FAST_BOWLER, battingSkill: 32, secondarySkill: 72, style: 'N', isOpener: false, isForeign: true, age: 36, fielding: 75, accuracy: 78, potential: 75 },
    { id: 'en-21', name: 'P. Overtonic', nationality: 'England', role: PlayerRole.FAST_BOWLER, battingSkill: 27, secondarySkill: 74, style: 'D', isOpener: false, isForeign: true, age: 32, fielding: 68, accuracy: 75, potential: 78 },
    { id: 'en-22', name: 'H. Brookton', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 68, secondarySkill: 18, style: 'A', isOpener: false, isForeign: true, age: 27, fielding: 72, accuracy: 40, potential: 90 },
    { id: 'en-23', name: 'J. Vinceley', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 66, secondarySkill: 15, style: 'N', isOpener: false, isForeign: true, age: 35, fielding: 75, accuracy: 35, potential: 75 },
    { id: 'en-24', name: 'T. Lawrence', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 64, secondarySkill: 20, style: 'N', isOpener: false, isForeign: true, age: 28, fielding: 68, accuracy: 42, potential: 78 },
    { id: 'en-25', name: 'B. Duckettson', nationality: 'England', role: PlayerRole.BATSMAN, battingSkill: 65, secondarySkill: 10, style: 'A', isOpener: false, isForeign: true, age: 31, fielding: 60, accuracy: 30, potential: 76 },
    { id: 'en-26', name: 'Parkinsonic', nationality: 'England', role: PlayerRole.SPIN_BOWLER, battingSkill: 35, secondarySkill: 66, style: 'D', isOpener: false, isForeign: true, age: 29, fielding: 55, accuracy: 72, potential: 74 },
    { id: 'en-27', name: 'Jordanic', nationality: 'England', role: PlayerRole.FAST_BOWLER, battingSkill: 29, secondarySkill: 70, style: 'N', isOpener: false, isForeign: true, age: 37, fielding: 85, accuracy: 65, potential: 70 },
    { id: 'en-28', name: 'Saltley', nationality: 'England', role: PlayerRole.WICKET_KEEPER, battingSkill: 62, secondarySkill: 68, style: 'A', isOpener: false, isForeign: true, age: 29, fielding: 78, accuracy: 45, potential: 82 },

    // AUSTRALIA
    { id: 'au-1', name: 'K. Rowden', nationality: 'Australia', role: PlayerRole.BATSMAN, battingSkill: 71, secondarySkill: 12, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 68, accuracy: 30, potential: 82 },
    { id: 'au-2', name: 'D. Fraser', nationality: 'Australia', role: PlayerRole.BATSMAN, battingSkill: 68, secondarySkill: 18, style: 'D', isOpener: false, isForeign: true, age: 22, fielding: 65, accuracy: 35, potential: 78 },
    { id: 'au-3', name: 'T. O’Neil', nationality: 'Australia', role: PlayerRole.BATSMAN, battingSkill: 66, secondarySkill: 10, style: 'A', isOpener: false, isForeign: true, age: 26, fielding: 60, accuracy: 30, potential: 75 },
    { id: 'au-4', name: 'S. Molnar', nationality: 'Australia', role: PlayerRole.WICKET_KEEPER, battingSkill: 65, secondarySkill: 72, style: 'A', isOpener: false, isForeign: true, age: 23, fielding: 80, accuracy: 45, potential: 80 },
    { id: 'au-5', name: 'R. Hughes', nationality: 'Australia', role: PlayerRole.WICKET_KEEPER, battingSkill: 62, secondarySkill: 68, style: 'D', isOpener: false, isForeign: true, age: 25, fielding: 75, accuracy: 42, potential: 72 },
    { id: 'au-6', name: 'P. Connell', nationality: 'Australia', role: PlayerRole.ALL_ROUNDER, battingSkill: 60, secondarySkill: 58, style: 'N', isOpener: false, isForeign: true, age: 21, fielding: 65, accuracy: 60, potential: 74 },
    { id: 'au-7', name: 'R. Steele', nationality: 'Australia', role: PlayerRole.ALL_ROUNDER, battingSkill: 63, secondarySkill: 61, style: 'D', isOpener: false, isForeign: true, age: 24, fielding: 68, accuracy: 62, potential: 76 },
    { id: 'au-8', name: 'N. Clarke', nationality: 'Australia', role: PlayerRole.SPIN_BOWLER, battingSkill: 44, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 27, fielding: 60, accuracy: 74, potential: 78 },
    { id: 'au-9', name: 'L. Sandhu', nationality: 'Australia', role: PlayerRole.SPIN_BOWLER, battingSkill: 40, secondarySkill: 70, style: 'D', isOpener: false, isForeign: true, age: 28, fielding: 62, accuracy: 76, potential: 72 },
    { id: 'au-10', name: 'J. Morris', nationality: 'Australia', role: PlayerRole.SPIN_BOWLER, battingSkill: 38, secondarySkill: 66, style: 'N', isOpener: false, isForeign: true, age: 22, fielding: 55, accuracy: 70, potential: 75 },
    { id: 'au-11', name: 'S. Cartwright', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 30, secondarySkill: 70, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 58, accuracy: 72, potential: 78 },
    { id: 'au-12', name: 'M. Doyle', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 28, secondarySkill: 66, style: 'D', isOpener: false, isForeign: true, age: 25, fielding: 55, accuracy: 68, potential: 70 },
    { id: 'au-13', name: 'H. Price', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 35, secondarySkill: 65, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 52, accuracy: 64, potential: 76 },
    { id: 'au-14', name: 'E. Norton', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 26, secondarySkill: 67, style: 'D', isOpener: false, isForeign: true, age: 21, fielding: 50, accuracy: 68, potential: 80 },
    { id: 'au-15', name: 'T. Walsh', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 29, secondarySkill: 64, style: 'N', isOpener: false, isForeign: true, age: 26, fielding: 54, accuracy: 62, potential: 72 },
    { id: 'au-16', name: 'J. Keaton', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 31, secondarySkill: 63, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 56, accuracy: 60, potential: 74 },
    { id: 'au-17', name: 'Bowen', nationality: 'Australia', role: PlayerRole.FAST_BOWLER, battingSkill: 24, secondarySkill: 62, style: 'D', isOpener: false, isForeign: true, age: 20, fielding: 50, accuracy: 60, potential: 78 },
    { id: 'au-18', name: 'C. Voss', nationality: 'Australia', role: PlayerRole.ALL_ROUNDER, battingSkill: 58, secondarySkill: 55, style: 'NA', isOpener: false, isForeign: true, age: 25, fielding: 65, accuracy: 58, potential: 70 },
    { id: 'au-19', name: 'Langford', nationality: 'Australia', role: PlayerRole.BATSMAN, battingSkill: 64, secondarySkill: 20, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 62, accuracy: 40, potential: 76 },

    // NEW ZEALAND
    { id: 'nz-1', name: 'T. McAllum', nationality: 'New Zealand', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 15, style: 'N', isOpener: false, isForeign: true, age: 34, fielding: 74, accuracy: 35, potential: 80 },
    { id: 'nz-2', name: 'J. Rutter', nationality: 'New Zealand', role: PlayerRole.BATSMAN, battingSkill: 70, secondarySkill: 18, style: 'D', isOpener: false, isForeign: true, age: 27, fielding: 70, accuracy: 40, potential: 75 },
    { id: 'nz-3', name: 'P. Elson', nationality: 'New Zealand', role: PlayerRole.BATSMAN, battingSkill: 68, secondarySkill: 20, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 65, accuracy: 38, potential: 78 },
    { id: 'nz-4', name: 'M. Calder', nationality: 'New Zealand', role: PlayerRole.WICKET_KEEPER, battingSkill: 65, secondarySkill: 70, style: 'N', isOpener: false, isForeign: true, age: 28, fielding: 82, accuracy: 45, potential: 75 },
    { id: 'nz-5', name: 'J. Moana', nationality: 'New Zealand', role: PlayerRole.ALL_ROUNDER, battingSkill: 60, secondarySkill: 58, style: 'NA', isOpener: false, isForeign: true, age: 24, fielding: 68, accuracy: 62, potential: 72 },
    { id: 'nz-6', name: 'R. Teague', nationality: 'New Zealand', role: PlayerRole.ALL_ROUNDER, battingSkill: 63, secondarySkill: 61, style: 'N', isOpener: false, isForeign: true, age: 29, fielding: 72, accuracy: 65, potential: 78 },
    { id: 'nz-7', name: 'L. Faulkner', nationality: 'New Zealand', role: PlayerRole.ALL_ROUNDER, battingSkill: 58, secondarySkill: 62, style: 'D', isOpener: false, isForeign: true, age: 35, fielding: 65, accuracy: 68, potential: 70 },
    { id: 'nz-8', name: 'K. Patel', nationality: 'New Zealand', role: PlayerRole.SPIN_BOWLER, battingSkill: 42, secondarySkill: 67, style: 'D', isOpener: false, isForeign: true, age: 37, fielding: 60, accuracy: 78, potential: 75 },
    { id: 'nz-9', name: 'N. Rawiri', nationality: 'New Zealand', role: PlayerRole.SPIN_BOWLER, battingSkill: 40, secondarySkill: 65, style: 'N', isOpener: false, isForeign: true, age: 22, fielding: 58, accuracy: 74, potential: 82 },
    { id: 'nz-10', name: 'A. Singh', nationality: 'New Zealand', role: PlayerRole.SPIN_BOWLER, battingSkill: 38, secondarySkill: 64, style: 'D', isOpener: false, isForeign: true, age: 26, fielding: 55, accuracy: 72, potential: 78 },
    { id: 'nz-11', name: 'H. McKay', nationality: 'New Zealand', role: PlayerRole.FAST_BOWLER, battingSkill: 28, secondarySkill: 70, style: 'D', isOpener: false, isForeign: true, age: 31, fielding: 62, accuracy: 75, potential: 72 },
    { id: 'nz-12', name: 'T. Ransom', nationality: 'New Zealand', role: PlayerRole.FAST_BOWLER, battingSkill: 30, secondarySkill: 68, style: 'N', isOpener: false, isForeign: true, age: 23, fielding: 60, accuracy: 72, potential: 80 },
    { id: 'nz-13', name: 'O. Bennett', nationality: 'New Zealand', role: PlayerRole.FAST_BOWLER, battingSkill: 26, secondarySkill: 66, style: 'D', isOpener: false, isForeign: true, age: 21, fielding: 52, accuracy: 70, potential: 76 },
    { id: 'nz-14', name: ' Whittaker', nationality: 'New Zealand', role: PlayerRole.FAST_BOWLER, battingSkill: 29, secondarySkill: 65, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 54, accuracy: 64, potential: 74 },
    { id: 'nz-15', name: 'E. Foster', nationality: 'New Zealand', role: PlayerRole.FAST_BOWLER, battingSkill: 27, secondarySkill: 64, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 56, accuracy: 62, potential: 72 },
    { id: 'nz-16', name: 'R. Collins', nationality: 'New Zealand', role: PlayerRole.FAST_BOWLER, battingSkill: 24, secondarySkill: 63, style: 'D', isOpener: false, isForeign: true, age: 20, fielding: 50, accuracy: 60, potential: 78 },
    { id: 'nz-17', name: 'Lawson', nationality: 'New Zealand', role: PlayerRole.BATSMAN, battingSkill: 66, secondarySkill: 22, style: 'N', isOpener: false, isForeign: true, age: 27, fielding: 65, accuracy: 42, potential: 76 },
    { id: 'nz-18', name: 'S. Grant', nationality: 'New Zealand', role: PlayerRole.ALL_ROUNDER, battingSkill: 59, secondarySkill: 55, style: 'NA', isOpener: false, isForeign: true, age: 25, fielding: 62, accuracy: 58, potential: 70 },
    { id: 'nz-19', name: 'M. Keane', nationality: 'New Zealand', role: PlayerRole.BATSMAN, battingSkill: 62, secondarySkill: 18, style: 'A', isOpener: false, isForeign: true, age: 23, fielding: 65, accuracy: 38, potential: 74 },
    { id: 'nz-20', name: 'Harper', nationality: 'New Zealand', role: PlayerRole.FAST_BOWLER, battingSkill: 25, secondarySkill: 62, style: 'D', isOpener: false, isForeign: true, age: 22, fielding: 53, accuracy: 60, potential: 75 },
    { id: 'nz-21', name: 'P. Nolan', nationality: 'New Zealand', role: PlayerRole.SPIN_BOWLER, battingSkill: 36, secondarySkill: 61, style: 'N', isOpener: false, isForeign: true, age: 28, fielding: 55, accuracy: 68, potential: 72 },
    { id: 'nz-22', name: 'Oakes', nationality: 'New Zealand', role: PlayerRole.BATSMAN, battingSkill: 60, secondarySkill: 12, style: 'N', isOpener: false, isForeign: true, age: 25, fielding: 62, accuracy: 30, potential: 70 },
    { id: 'nz-23', name: 'Ward', nationality: 'New Zealand', role: PlayerRole.ALL_ROUNDER, battingSkill: 57, secondarySkill: 54, style: 'N', isOpener: false, isForeign: true, age: 24, fielding: 61, accuracy: 56, potential: 73 },
    { id: 'nz-24', name: 'Moore', nationality: 'New Zealand', role: PlayerRole.WICKET_KEEPER, battingSkill: 58, secondarySkill: 66, style: 'D', isOpener: false, isForeign: true, age: 29, fielding: 70, accuracy: 45, potential: 72 },

    // SPIN BOWLERS (LOCAL)
    { id: 'sb-1', name: 'Rahat', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 12, secondarySkill: 59, style: 'N', isOpener: false, isForeign: false, age: 22, fielding: 55, accuracy: 68, potential: 75 },
    { id: 'sb-2', name: 'Abrar', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 22, secondarySkill: 62, style: 'D', isOpener: false, isForeign: false, age: 24, fielding: 45, accuracy: 74, potential: 78 },
    { id: 'sb-3', name: 'Anwar', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 28, secondarySkill: 81, style: 'N', isOpener: false, isForeign: false, age: 27, fielding: 60, accuracy: 88, potential: 88 },
    { id: 'sb-4', name: 'Arshad', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 22, secondarySkill: 56, style: 'D', isOpener: false, isForeign: false, age: 21, fielding: 50, accuracy: 62, potential: 72 },
    { id: 'sb-5', name: 'Mehrab', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 16, secondarySkill: 62, style: 'D', isOpener: false, isForeign: false, age: 23, fielding: 48, accuracy: 70, potential: 76 },
    { id: 'sb-6', name: 'Bilal', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 40, secondarySkill: 78, style: 'N', isOpener: false, isForeign: false, age: 26, fielding: 65, accuracy: 82, potential: 84 },
    { id: 'sb-7', name: 'Adnan', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 12, secondarySkill: 56, style: 'D', isOpener: false, isForeign: false, age: 20, fielding: 42, accuracy: 64, potential: 74 },
    { id: 'sb-8', name: 'Riaz', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 11, secondarySkill: 55, style: 'N', isOpener: false, isForeign: false, age: 19, fielding: 50, accuracy: 60, potential: 78 },
    { id: 'sb-9', name: 'Amjad', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 30, secondarySkill: 69, style: 'D', isOpener: false, isForeign: false, age: 28, fielding: 55, accuracy: 76, potential: 76 },
    { id: 'sb-10', name: 'Rehan', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 12, secondarySkill: 61, style: 'D', isOpener: false, isForeign: false, age: 23, fielding: 52, accuracy: 72, potential: 80 },
    { id: 'sb-11', name: 'N. Samad', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 23, secondarySkill: 55, style: 'D', isOpener: false, isForeign: false, age: 22, fielding: 50, accuracy: 60, potential: 72 },
    { id: 'sb-12', name: 'M. Amjad', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 45, secondarySkill: 68, style: 'N', isOpener: false, isForeign: false, age: 29, fielding: 60, accuracy: 75, potential: 75 },
    { id: 'sb-13', name: 'Asim', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 23, secondarySkill: 71, style: 'D', isOpener: false, isForeign: false, age: 25, fielding: 58, accuracy: 78, potential: 82 },

    // ALL-ROUNDERS (LOCAL)
    { id: 'ar-1', name: 'Khalid', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 54, secondarySkill: 45, style: 'N', isOpener: false, isForeign: false, age: 23, fielding: 65, accuracy: 55, potential: 70 },
    { id: 'ar-2', name: 'Taimoor', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 56, secondarySkill: 51, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 62, accuracy: 60, potential: 72 },
    { id: 'ar-3', name: 'Saeed', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 60, secondarySkill: 58, style: 'N', isOpener: false, isForeign: false, age: 26, fielding: 68, accuracy: 65, potential: 75 },
    { id: 'ar-4', name: 'Najaf', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 41, secondarySkill: 63, style: 'D', isOpener: false, isForeign: false, age: 22, fielding: 55, accuracy: 70, potential: 78 },
    { id: 'ar-5', name: 'Jahangir', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 60, secondarySkill: 58, style: 'D', isOpener: false, isForeign: false, age: 30, fielding: 60, accuracy: 62, potential: 65 },
    { id: 'ar-6', name: 'M. Asghar', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 56, secondarySkill: 55, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 63, accuracy: 62, potential: 74 },
    { id: 'ar-7', name: 'Amir', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 81, secondarySkill: 85, style: 'NA', isOpener: false, isForeign: false, age: 28, fielding: 85, accuracy: 88, potential: 92 },
    { id: 'ar-8', name: 'Mansoor', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 55, secondarySkill: 65, style: 'N', isOpener: false, isForeign: false, age: 27, fielding: 70, accuracy: 72, potential: 78 },
    { id: 'ar-9', name: 'Aftab', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 70, secondarySkill: 61, style: 'NA', isOpener: true, isForeign: false, age: 26, fielding: 75, accuracy: 65, potential: 82 },
    { id: 'ar-10', name: 'Wahab', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 50, secondarySkill: 51, style: 'N', isOpener: false, isForeign: false, age: 22, fielding: 58, accuracy: 55, potential: 74 },
    { id: 'ar-11', name: 'Aaqib Raza', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 78, secondarySkill: 70, style: 'A', isOpener: false, isForeign: false, age: 25, fielding: 80, accuracy: 78, potential: 86 },
    { id: 'ar-12', name: 'Sike', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 87, secondarySkill: 85, style: 'NA', isOpener: true, isForeign: false, age: 29, fielding: 90, accuracy: 92, potential: 95 },
    { id: 'ar-13', name: 'Nawaz', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 57, secondarySkill: 67, style: 'A', isOpener: false, isForeign: false, age: 27, fielding: 68, accuracy: 75, potential: 80 },
    { id: 'ar-14', name: 'Muhammad Tahir', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 60, secondarySkill: 56, style: 'A', isOpener: false, isForeign: false, age: 23, fielding: 65, accuracy: 62, potential: 75 },
    { id: 'ar-15', name: 'Irfaan Ali', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 70, secondarySkill: 56, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 72, accuracy: 60, potential: 80 },

    // WICKET KEEPERS (LOCAL)
    { id: 'wk-1', name: 'M. Imran', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 68, secondarySkill: 60, style: 'A', isOpener: false, isForeign: false, age: 25, fielding: 78, accuracy: 40, potential: 80 },
    { id: 'wk-2', name: 'S. Khan', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 75, secondarySkill: 87, style: 'D', isOpener: true, isForeign: false, age: 30, fielding: 92, accuracy: 50, potential: 90 },
    { id: 'wk-3', name: 'Ali', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 60, secondarySkill: 67, style: 'D', isOpener: false, isForeign: false, age: 22, fielding: 75, accuracy: 45, potential: 78 },
    { id: 'wk-4', name: 'A. Sajjad', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 55, secondarySkill: 69, style: 'N', isOpener: false, isForeign: false, age: 23, fielding: 72, accuracy: 40, potential: 75 },
    { id: 'wk-5', name: 'Zulqarnain', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 70, secondarySkill: 78, style: 'N', isOpener: true, isForeign: false, age: 26, fielding: 85, accuracy: 50, potential: 85 },
    { id: 'wk-6', name: 'Haseebullah', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 72, secondarySkill: 78, style: 'NA', isOpener: true, isForeign: false, age: 24, fielding: 82, accuracy: 55, potential: 88 },
    { id: 'wk-7', name: 'Shahid Latif', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 59, secondarySkill: 67, style: 'N', isOpener: false, isForeign: false, age: 28, fielding: 78, accuracy: 40, potential: 72 },
    { id: 'wk-8', name: 'Yaqoob', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 63, secondarySkill: 68, style: 'D', isOpener: false, isForeign: false, age: 25, fielding: 75, accuracy: 45, potential: 78 },
    { id: 'wk-9', name: 'I. Javed', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 84, secondarySkill: 85, style: 'NA', isOpener: true, isForeign: false, age: 31, fielding: 95, accuracy: 60, potential: 90 },
    { id: 'wk-10', name: 'M. Amin', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 79, secondarySkill: 80, style: 'NA', isOpener: true, isForeign: false, age: 27, fielding: 88, accuracy: 58, potential: 88 },
    { id: 'wk-11', name: 'Aslam Sattar', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 55, secondarySkill: 60, style: 'D', isOpener: false, isForeign: false, age: 22, fielding: 68, accuracy: 40, potential: 75 },
    { id: 'wk-12', name: 'Atiq Ali', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 62, secondarySkill: 72, style: 'N', isOpener: true, isForeign: false, age: 24, fielding: 80, accuracy: 48, potential: 82 },
    { id: 'wk-13', name: 'Zahid', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 77, secondarySkill: 76, style: 'N', isOpener: true, isForeign: false, age: 28, fielding: 82, accuracy: 50, potential: 84 },
    { id: 'wk-14', name: 'Uddin Ali', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 55, secondarySkill: 65, style: 'N', isOpener: true, isForeign: false, age: 21, fielding: 74, accuracy: 40, potential: 80 },
    { id: 'wk-15', name: 'R. Saad', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 60, secondarySkill: 70, style: 'N', isOpener: false, isForeign: false, age: 22, fielding: 78, accuracy: 45, potential: 78 },

    // FAST BOWLERS (LOCAL)
    { id: 'bl-1', name: 'Ilyas', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 11, secondarySkill: 63, style: 'D', isOpener: false, isForeign: false, age: 23, fielding: 50, accuracy: 70, potential: 80 },
    { id: 'bl-2', name: 'Waheed', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 10, secondarySkill: 55, style: 'D', isOpener: false, isForeign: false, age: 21, fielding: 45, accuracy: 62, potential: 74 },
    { id: 'bl-3', name: 'M. Ali', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 23, secondarySkill: 67, style: 'D', isOpener: false, isForeign: false, age: 24, fielding: 55, accuracy: 74, potential: 78 },
    { id: 'bl-4', name: 'Sohail', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 24, secondarySkill: 75, style: 'D', isOpener: false, isForeign: false, age: 26, fielding: 60, accuracy: 82, potential: 82 },
    { id: 'bl-5', name: 'Zia', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 23, secondarySkill: 72, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 58, accuracy: 80, potential: 84 },
    { id: 'bl-6', name: 'Azam', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 23, secondarySkill: 70, style: 'D', isOpener: false, isForeign: false, age: 27, fielding: 62, accuracy: 78, potential: 78 },
    { id: 'bl-7', name: 'Faraz Khan', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 12, secondarySkill: 56, style: 'N', isOpener: false, isForeign: false, age: 20, fielding: 48, accuracy: 65, potential: 76 },
    { id: 'bl-8', name: 'Waleed', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 23, secondarySkill: 55, style: 'D', isOpener: false, isForeign: false, age: 19, fielding: 42, accuracy: 60, potential: 78 },
    { id: 'bl-9', name: 'Atif Maqbool', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 12, secondarySkill: 53, style: 'N', isOpener: false, isForeign: false, age: 22, fielding: 45, accuracy: 58, potential: 72 },
    { id: 'bl-10', name: 'Rizwan', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 70, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 55, accuracy: 76, potential: 82 },
    { id: 'bl-11', name: 'Salman', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 30, secondarySkill: 73, style: 'D', isOpener: false, isForeign: false, age: 28, fielding: 62, accuracy: 80, potential: 80 },
    { id: 'bl-12', name: 'Naseem', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 81, style: 'D', isOpener: false, isForeign: false, age: 26, fielding: 65, accuracy: 88, potential: 92 },
    { id: 'bl-13', name: 'Aramzad', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 25, secondarySkill: 85, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 68, accuracy: 92, potential: 95 },
    { id: 'bl-14', name: 'M. Arif', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 12, secondarySkill: 55, style: 'D', isOpener: false, isForeign: false, age: 20, fielding: 44, accuracy: 62, potential: 74 },
    { id: 'bl-15', name: 'Waheed (2)', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 16, secondarySkill: 59, style: 'D', isOpener: false, isForeign: false, age: 23, fielding: 50, accuracy: 68, potential: 72 },
    { id: 'bl-16', name: 'Naeem', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 75, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 60, accuracy: 82, potential: 82 },
    { id: 'bl-17', name: 'Akhlaq', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 69, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 58, accuracy: 75, potential: 78 },
    { id: 'bl-18', name: 'Ahsan', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 78, style: 'N', isOpener: false, isForeign: false, age: 27, fielding: 62, accuracy: 85, potential: 88 },
    { id: 'bl-19', name: 'Farhan', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 24, secondarySkill: 80, style: 'N', isOpener: false, isForeign: false, age: 26, fielding: 65, accuracy: 88, potential: 90 },
    { id: 'bl-20', name: 'N. Javed', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 49, style: 'D', isOpener: false, isForeign: false, age: 21, fielding: 48, accuracy: 55, potential: 70 },
    { id: 'bl-21', name: 'Sohail Ahmed', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 23, secondarySkill: 46, style: 'D', isOpener: false, isForeign: false, age: 22, fielding: 45, accuracy: 52, potential: 72 },
    { id: 'bl-22', name: 'Muzafar', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 71, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 58, accuracy: 78, potential: 82 },
    { id: 'bl-23', name: 'Sameen', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 22, secondarySkill: 72, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 60, accuracy: 80, potential: 80 },
    { id: 'bl-24', name: 'Zohaib', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 36, secondarySkill: 85, style: 'N', isOpener: false, isForeign: false, age: 28, fielding: 75, accuracy: 90, potential: 92 },
    { id: 'bl-25', name: 'Iqrar', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 19, secondarySkill: 90, style: 'D', isOpener: false, isForeign: false, age: 29, fielding: 82, accuracy: 95, potential: 95 },

    // BATSMEN (LOCAL)
    { id: 'bt-1', name: 'Jahid', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 61, secondarySkill: 22, style: 'A', isOpener: false, isForeign: false, age: 23, fielding: 60, accuracy: 40, potential: 75 },
    { id: 'bt-2', name: 'Shahid', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 68, secondarySkill: 45, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 65, accuracy: 50, potential: 78 },
    { id: 'bt-3', name: 'Altaf', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 55, secondarySkill: 10, style: 'N', isOpener: true, isForeign: false, age: 22, fielding: 58, accuracy: 30, potential: 72 },
    { id: 'bt-4', name: 'Yasir', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 67, secondarySkill: 12, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 62, accuracy: 32, potential: 78 },
    { id: 'bt-5', name: 'Nauman', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 12, style: 'N', isOpener: true, isForeign: false, age: 26, fielding: 68, accuracy: 30, potential: 82 },
    { id: 'bt-6', name: 'Nasir', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 81, secondarySkill: 48, style: 'NA', isOpener: true, isForeign: false, age: 29, fielding: 75, accuracy: 55, potential: 88 },
    { id: 'bt-7', name: 'Haider', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 62, secondarySkill: 25, style: 'N', isOpener: true, isForeign: false, age: 21, fielding: 70, accuracy: 42, potential: 85 },
    { id: 'bt-8', name: 'Asad', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 60, secondarySkill: 11, style: 'N', isOpener: true, isForeign: false, age: 23, fielding: 65, accuracy: 30, potential: 78 },
    { id: 'bt-9', name: 'Siraj', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 63, secondarySkill: 22, style: 'D', isOpener: true, isForeign: false, age: 25, fielding: 62, accuracy: 40, potential: 74 },
    { id: 'bt-10', name: 'Aziz', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 53, secondarySkill: 22, style: 'A', isOpener: false, isForeign: false, age: 22, fielding: 55, accuracy: 40, potential: 70 },
    { id: 'bt-11', name: 'Aslam', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 71, secondarySkill: 12, style: 'D', isOpener: false, isForeign: false, age: 28, fielding: 70, accuracy: 35, potential: 78 },
    { id: 'bt-12', name: 'Abid', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 79, secondarySkill: 45, style: 'NA', isOpener: true, isForeign: false, age: 27, fielding: 75, accuracy: 50, potential: 85 },
    { id: 'bt-13', name: 'Husnain', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 22, style: 'A', isOpener: false, isForeign: false, age: 24, fielding: 68, accuracy: 42, potential: 82 },
    { id: 'bt-14', name: 'Qasim', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 45, secondarySkill: 12, style: 'N', isOpener: false, isForeign: false, age: 20, fielding: 52, accuracy: 30, potential: 72 },
    { id: 'bt-15', name: 'K. Navid', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 45, style: 'N', isOpener: false, isForeign: false, age: 26, fielding: 70, accuracy: 50, potential: 80 },
    { id: 'bt-16', name: 'Shoaib Khan', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 56, secondarySkill: 25, style: 'D', isOpener: false, isForeign: false, age: 25, fielding: 60, accuracy: 42, potential: 70 },
    { id: 'bt-17', name: 'A. Usman', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 53, secondarySkill: 22, style: 'N', isOpener: true, isForeign: false, age: 23, fielding: 58, accuracy: 40, potential: 68 },
    { id: 'bt-18', name: 'Aafaq', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 50, secondarySkill: 10, style: 'D', isOpener: false, isForeign: false, age: 22, fielding: 55, accuracy: 30, potential: 65 },
    { id: 'bt-19', name: 'Fakhrudin', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 70, secondarySkill: 23, style: 'D', isOpener: false, isForeign: false, age: 28, fielding: 65, accuracy: 40, potential: 75 },
    { id: 'bt-20', name: 'A. Hafeez', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 68, secondarySkill: 11, style: 'N', isOpener: true, isForeign: false, age: 30, fielding: 70, accuracy: 30, potential: 72 },
    { id: 'bt-21', name: 'Hamid Hasan', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 70, secondarySkill: 10, style: 'A', isOpener: false, isForeign: false, age: 27, fielding: 72, accuracy: 30, potential: 80 },
    { id: 'bt-22', name: 'S. Hasan', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 65, secondarySkill: 10, style: 'D', isOpener: false, isForeign: false, age: 25, fielding: 68, accuracy: 30, potential: 75 },
    { id: 'bt-23', name: 'Zakir', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 59, secondarySkill: 11, style: 'D', isOpener: false, isForeign: false, age: 24, fielding: 62, accuracy: 32, potential: 72 },
    { id: 'bt-24', name: 'Sadiq', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 46, secondarySkill: 10, style: 'D', isOpener: false, isForeign: false, age: 21, fielding: 52, accuracy: 30, potential: 68 },
    { id: 'bt-25', name: 'A. Jamal', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 59, secondarySkill: 0, style: 'A', isOpener: false, isForeign: false, age: 23, fielding: 65, accuracy: 20, potential: 76 },
    { id: 'bt-26', name: 'Ashfaq', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 55, secondarySkill: 10, style: 'D', isOpener: false, isForeign: false, age: 24, fielding: 60, accuracy: 30, potential: 70 },
    { id: 'bt-27', name: 'Farhan', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 78, secondarySkill: 10, style: 'N', isOpener: true, isForeign: false, age: 27, fielding: 75, accuracy: 30, potential: 84 },
    { id: 'bt-28', name: 'M. Musa', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 8, style: 'A', isOpener: false, isForeign: false, age: 22, fielding: 70, accuracy: 25, potential: 85 },
    { id: 'bt-29', name: 'Abass', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 72, secondarySkill: 0, style: 'A', isOpener: false, isForeign: false, age: 23, fielding: 68, accuracy: 20, potential: 82 },
    { id: 'bt-30', name: 'Faisal Hasan', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 83, secondarySkill: 60, style: 'NA', isOpener: true, isForeign: false, age: 29, fielding: 85, accuracy: 65, potential: 90 },
    { id: 'bt-31', name: 'Muhammad Shahzain', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 70, secondarySkill: 34, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 72, accuracy: 48, potential: 84 },
    { id: 'bt-32', name: 'Azhar', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 75, secondarySkill: 45, style: 'A', isOpener: false, isForeign: false, age: 27, fielding: 78, accuracy: 55, potential: 82 },
    
    // PAKISTANI LOCAL FREE AGENTS (BALANCED <60)
    // Openers
    { id: 'pk-fa-1', name: 'Ahsan Qureshi', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 58, secondarySkill: 20, style: 'D', isOpener: true, isForeign: false, age: 24, fielding: 58, accuracy: 45, potential: 72 },
    { id: 'pk-fa-2', name: 'Zeeshan Malik', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 55, secondarySkill: 15, style: 'N', isOpener: true, isForeign: false, age: 22, fielding: 60, accuracy: 40, potential: 75 },
    { id: 'pk-fa-3', name: 'Imran Latif', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 57, secondarySkill: 10, style: 'A', isOpener: true, isForeign: false, age: 26, fielding: 55, accuracy: 35, potential: 70 },
    { id: 'pk-fa-4', name: 'Adnan Sheikh', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 56, secondarySkill: 25, style: 'N', isOpener: true, isForeign: false, age: 23, fielding: 62, accuracy: 48, potential: 74 },
    { id: 'pk-fa-5', name: 'Sajid Farooq', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 59, secondarySkill: 22, style: 'D', isOpener: true, isForeign: false, age: 25, fielding: 57, accuracy: 42, potential: 73 },
    
    // Middle / Lower Order
    { id: 'pk-fa-6', name: 'Rashid Nawaz', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 53, secondarySkill: 18, style: 'N', isOpener: false, isForeign: false, age: 21, fielding: 55, accuracy: 40, potential: 68 },
    { id: 'pk-fa-7', name: 'Kamran Siddiqui', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 54, secondarySkill: 28, style: 'D', isOpener: false, isForeign: false, age: 24, fielding: 58, accuracy: 45, potential: 70 },
    { id: 'pk-fa-8', name: 'Noman Ali', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 51, secondarySkill: 20, style: 'A', isOpener: false, isForeign: false, age: 22, fielding: 54, accuracy: 38, potential: 69 },
    { id: 'pk-fa-9', name: 'Shahid Hussain', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 56, secondarySkill: 30, style: 'N', isOpener: false, isForeign: false, age: 27, fielding: 60, accuracy: 50, potential: 72 },
    { id: 'pk-fa-10', name: 'Aqib Jatoi', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 52, secondarySkill: 15, style: 'A', isOpener: false, isForeign: false, age: 20, fielding: 52, accuracy: 35, potential: 75 },
    { id: 'pk-fa-11', name: 'Bilal Ahmed', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 50, secondarySkill: 18, style: 'D', isOpener: false, isForeign: false, age: 19, fielding: 50, accuracy: 36, potential: 74 },
    { id: 'pk-fa-12', name: 'Tariq Hanif', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 55, secondarySkill: 27, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 59, accuracy: 46, potential: 71 },
    { id: 'pk-fa-13', name: 'Fahad Rafiq', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 57, secondarySkill: 21, style: 'N', isOpener: false, isForeign: false, age: 23, fielding: 61, accuracy: 40, potential: 76 },
    { id: 'pk-fa-14', name: 'Owais Bashir', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 54, secondarySkill: 24, style: 'A', isOpener: false, isForeign: false, age: 26, fielding: 56, accuracy: 42, potential: 70 },
    { id: 'pk-fa-15', name: 'Mehmood Aslam', nationality: 'Local', role: PlayerRole.BATSMAN, battingSkill: 53, secondarySkill: 29, style: 'D', isOpener: false, isForeign: false, age: 28, fielding: 57, accuracy: 48, potential: 68 },
    
    // Wicket Keepers
    { id: 'pk-fa-16', name: 'Hamza Iqbal', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 58, secondarySkill: 55, style: 'A', isOpener: false, isForeign: false, age: 22, fielding: 65, accuracy: 40, potential: 78 },
    { id: 'pk-fa-17', name: 'Usman Akhtar', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 56, secondarySkill: 58, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 62, accuracy: 45, potential: 75 },
    { id: 'pk-fa-18', name: 'Ali Raza', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 52, secondarySkill: 62, style: 'D', isOpener: false, isForeign: false, age: 21, fielding: 68, accuracy: 42, potential: 77 },
    { id: 'pk-fa-19', name: 'Yasir Shahid', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 55, secondarySkill: 60, style: 'A', isOpener: false, isForeign: false, age: 23, fielding: 63, accuracy: 44, potential: 74 },
    { id: 'pk-fa-20', name: 'Kashif Nawaz', nationality: 'Local', role: PlayerRole.WICKET_KEEPER, battingSkill: 54, secondarySkill: 56, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 61, accuracy: 41, potential: 72 },
    
    // All-Rounders
    { id: 'pk-fa-21', name: 'Mubashir Khan', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 58, secondarySkill: 56, style: 'N', isOpener: false, isForeign: false, age: 23, fielding: 60, accuracy: 55, potential: 76 },
    { id: 'pk-fa-22', name: 'Naveed Anwar', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 52, secondarySkill: 53, style: 'D', isOpener: false, isForeign: false, age: 25, fielding: 58, accuracy: 52, potential: 71 },
    { id: 'pk-fa-23', name: 'Haris Siddiqui', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 54, secondarySkill: 55, style: 'A', isOpener: false, isForeign: false, age: 21, fielding: 62, accuracy: 54, potential: 78 },
    { id: 'pk-fa-24', name: 'Farhan Ali', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 53, secondarySkill: 52, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 57, accuracy: 51, potential: 73 },
    { id: 'pk-fa-25', name: 'Umer Shahzad', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 57, secondarySkill: 54, style: 'N', isOpener: false, isForeign: false, age: 22, fielding: 61, accuracy: 53, potential: 75 },
    { id: 'pk-fa-26', name: 'Adeel Farooq', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 55, secondarySkill: 58, style: 'D', isOpener: false, isForeign: false, age: 26, fielding: 56, accuracy: 57, potential: 69 },
    { id: 'pk-fa-27', name: 'Saad Hussain', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 56, secondarySkill: 53, style: 'A', isOpener: false, isForeign: false, age: 23, fielding: 59, accuracy: 52, potential: 74 },
    { id: 'pk-fa-28', name: 'Rizwan Khalid', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 50, secondarySkill: 51, style: 'D', isOpener: false, isForeign: false, age: 19, fielding: 54, accuracy: 50, potential: 77 },
    { id: 'pk-fa-29', name: 'Shahbaz Ahmed', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 52, secondarySkill: 57, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 55, accuracy: 56, potential: 72 },
    { id: 'pk-fa-30', name: 'Junaid Hanif', nationality: 'Local', role: PlayerRole.ALL_ROUNDER, battingSkill: 59, secondarySkill: 55, style: 'A', isOpener: false, isForeign: false, age: 25, fielding: 63, accuracy: 54, potential: 75 },
    
    // Spinners
    { id: 'pk-fa-31', name: 'Imtiaz Baloch', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 48, secondarySkill: 58, style: 'N', isOpener: false, isForeign: false, age: 28, fielding: 52, accuracy: 60, potential: 65 },
    { id: 'pk-fa-32', name: 'Salman Rafiq', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 51, secondarySkill: 56, style: 'D', isOpener: false, isForeign: false, age: 23, fielding: 55, accuracy: 58, potential: 74 },
    { id: 'pk-fa-33', name: 'Mohsin Ali', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 54, secondarySkill: 53, style: 'A', isOpener: false, isForeign: false, age: 22, fielding: 58, accuracy: 54, potential: 78 },
    { id: 'pk-fa-34', name: 'Younis Qadir', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 49, secondarySkill: 57, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 51, accuracy: 59, potential: 70 },
    { id: 'pk-fa-35', name: 'Faisal Mehmood', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 52, secondarySkill: 54, style: 'D', isOpener: false, isForeign: false, age: 26, fielding: 53, accuracy: 56, potential: 68 },
    { id: 'pk-fa-36', name: 'Asad Niazi', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 50, secondarySkill: 52, style: 'N', isOpener: false, isForeign: false, age: 21, fielding: 50, accuracy: 54, potential: 75 },
    { id: 'pk-fa-37', name: 'Nadeem Arif', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 51, secondarySkill: 58, style: 'A', isOpener: false, isForeign: false, age: 24, fielding: 54, accuracy: 62, potential: 73 },
    { id: 'pk-fa-38', name: 'Tauseef Hussain', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 53, secondarySkill: 56, style: 'D', isOpener: false, isForeign: false, age: 27, fielding: 56, accuracy: 59, potential: 69 },
    { id: 'pk-fa-39', name: 'Amir Javed', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 52, secondarySkill: 55, style: 'N', isOpener: false, isForeign: false, age: 23, fielding: 55, accuracy: 57, potential: 72 },
    { id: 'pk-fa-40', name: 'Hassan Zia', nationality: 'Local', role: PlayerRole.SPIN_BOWLER, battingSkill: 49, secondarySkill: 53, style: 'A', isOpener: false, isForeign: false, age: 20, fielding: 50, accuracy: 55, potential: 76 },
    
    // Fast Bowlers
    { id: 'pk-fa-41', name: 'Zubair Khan', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 35, secondarySkill: 58, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 50, accuracy: 60, potential: 70 },
    { id: 'pk-fa-42', name: 'Rashid Mehmood', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 42, secondarySkill: 56, style: 'A', isOpener: false, isForeign: false, age: 23, fielding: 52, accuracy: 58, potential: 72 },
    { id: 'pk-fa-43', name: 'Fahim Gul', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 33, secondarySkill: 55, style: 'A', isOpener: false, isForeign: false, age: 21, fielding: 48, accuracy: 56, potential: 75 },
    { id: 'pk-fa-44', name: 'Waseem Shah', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 40, secondarySkill: 57, style: 'N', isOpener: false, isForeign: false, age: 26, fielding: 55, accuracy: 62, potential: 74 },
    { id: 'pk-fa-45', name: 'Jahangir Ali', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 36, secondarySkill: 54, style: 'N', isOpener: false, isForeign: false, age: 24, fielding: 53, accuracy: 55, potential: 70 },
    { id: 'pk-fa-46', name: 'Hammad Rafiq', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 39, secondarySkill: 53, style: 'A', isOpener: false, isForeign: false, age: 22, fielding: 51, accuracy: 54, potential: 73 },
    { id: 'pk-fa-47', name: 'Zohaib Malik', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 32, secondarySkill: 52, style: 'N', isOpener: false, isForeign: false, age: 20, fielding: 47, accuracy: 53, potential: 76 },
    { id: 'pk-fa-48', name: 'Noman Shah', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 34, secondarySkill: 58, style: 'A', isOpener: false, isForeign: false, age: 27, fielding: 54, accuracy: 63, potential: 71 },
    { id: 'pk-fa-49', name: 'Irfan Qureshi', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 37, secondarySkill: 55, style: 'N', isOpener: false, isForeign: false, age: 25, fielding: 52, accuracy: 57, potential: 70 },
    { id: 'pk-fa-50', name: 'Adil Nawaz', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 41, secondarySkill: 53, style: 'A', isOpener: false, isForeign: false, age: 24, fielding: 56, accuracy: 55, potential: 72 },
    { id: 'pk-fa-51', name: 'Rauf Ahmed', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 36, secondarySkill: 51, style: 'N', isOpener: false, isForeign: false, age: 28, fielding: 51, accuracy: 52, potential: 65 },
    { id: 'pk-fa-52', name: 'Mansoor Iqbal', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 38, secondarySkill: 52, style: 'N', isOpener: false, isForeign: false, age: 23, fielding: 53, accuracy: 54, potential: 70 },
    { id: 'pk-fa-53', name: 'Asif Hanif', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 42, secondarySkill: 54, style: 'A', isOpener: false, isForeign: false, age: 25, fielding: 55, accuracy: 56, potential: 74 },
    { id: 'pk-fa-54', name: 'Qasim Ali', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 35, secondarySkill: 57, style: 'A', isOpener: false, isForeign: false, age: 22, fielding: 49, accuracy: 61, potential: 76 },
    { id: 'pk-fa-55', name: 'Tanveer Hussain', nationality: 'Local', role: PlayerRole.FAST_BOWLER, battingSkill: 39, secondarySkill: 50, style: 'N', isOpener: false, isForeign: false, age: 21, fielding: 51, accuracy: 50, potential: 73 }
];

export const PLAYERS: Player[] = playersRaw.map(p => ({
    ...p,
    isFreeAgent: true,
    stats: generateInitialStats()
}));

export const PRE_BUILT_SQUADS: Record<string, string[]> = {
  'team1': [],
  'team2': [],
  'team3': [],
  'team4': [],
  'team5': [],
  'team6': [],
  'team7': [],
  'team8': [],
  'team9': [],
  'team10': [],
  'team11': [],
  'team12': [],
  'team13': [],
  'team14': [],
  'team15': [],
  'team16': [],
};

export const INITIAL_NEWS: NewsArticle[] = [
    { id: 'n1', headline: "Season 26 Auction Concluded!", date: "28 Jun 2025", excerpt: "Teams have finalized their 16-man core squads.", content: "The hammer has fallen. Franchises have spent big to secure a mix of local grit and foreign flair. Minimum 7 Pakistani player rule was strictly enforced.", type: 'league' },
    { id: 'n2', headline: "Triple Format Challenge 26", date: "29 Jun 2025", excerpt: "Teams brace for T20, One-Day, and Shield formats.", content: "Consistency will be key. The season opens with T20, followed by One-Day, and concluding with the multi-day Shield.", type: 'league' },
    { id: 'n3', headline: "Global Stars Arrive", date: "30 Jun 2025", excerpt: "Haddin, Warner, Sprike and others touch down.", content: "The foreign contingent has arrived. With up to 6 foreign slots per playing XI, the pressure is on the international stars to perform.", type: 'league' },
];

export const NEWS_ARTICLES = INITIAL_NEWS;
